/*
 * BMS_Power_Control.c
 *
 *  Created on: Jul 10, 2023
 *      Author: TDM
 */

#include "BMS_Power_Control.h"
#include "main.h"

void TURN_OFF_ALL_MOSFETS(void){
	 HAL_GPIO_WritePin(TURN_OFF_DISCHARGE_GPIO_Port, TURN_OFF_DISCHARGE_Pin, GPIO_PIN_SET);
	 HAL_GPIO_WritePin(TURN_OFF_CHARGE_GPIO_Port, TURN_OFF_CHARGE_Pin, GPIO_PIN_SET);
	 HAL_GPIO_WritePin(TURN_ON_DISCHARGE_GPIO_Port, TURN_ON_DISCHARGE_Pin, GPIO_PIN_RESET);
	 HAL_GPIO_WritePin(TURN_ON_CHARGE_GPIO_Port, TURN_ON_CHARGE_Pin, GPIO_PIN_RESET);
	 HAL_Delay(10);
	 HAL_GPIO_WritePin(TURN_OFF_DISCHARGE_GPIO_Port, TURN_OFF_DISCHARGE_Pin, GPIO_PIN_RESET);
	 HAL_GPIO_WritePin(TURN_OFF_CHARGE_GPIO_Port, TURN_OFF_CHARGE_Pin, GPIO_PIN_RESET);
}

void TURN_ON_ALL_MOSFETS(void){
	 HAL_GPIO_WritePin(TURN_OFF_DISCHARGE_GPIO_Port, TURN_OFF_DISCHARGE_Pin, GPIO_PIN_RESET);
	 HAL_GPIO_WritePin(TURN_OFF_CHARGE_GPIO_Port, TURN_OFF_CHARGE_Pin, GPIO_PIN_RESET);
	 HAL_GPIO_WritePin(TURN_ON_DISCHARGE_GPIO_Port, TURN_ON_DISCHARGE_Pin, GPIO_PIN_SET);
	 HAL_GPIO_WritePin(TURN_ON_CHARGE_GPIO_Port, TURN_ON_CHARGE_Pin, GPIO_PIN_SET);
	 HAL_Delay(10);
	 HAL_GPIO_WritePin(TURN_ON_DISCHARGE_GPIO_Port, TURN_ON_DISCHARGE_Pin, GPIO_PIN_RESET);
	 HAL_GPIO_WritePin(TURN_ON_CHARGE_GPIO_Port, TURN_ON_CHARGE_Pin, GPIO_PIN_RESET);
}

void TURN_ON_CHARGE_MOSFET(void){
	 HAL_GPIO_WritePin(TURN_OFF_CHARGE_GPIO_Port, TURN_OFF_CHARGE_Pin, GPIO_PIN_RESET);
	 HAL_GPIO_WritePin(TURN_ON_CHARGE_GPIO_Port, TURN_ON_CHARGE_Pin, GPIO_PIN_SET);
	 HAL_Delay(10);
	 HAL_GPIO_WritePin(TURN_ON_CHARGE_GPIO_Port, TURN_ON_CHARGE_Pin, GPIO_PIN_RESET);
}

void TURN_ON_DISCHARGE_MOSFET(void){
	 HAL_GPIO_WritePin(TURN_OFF_DISCHARGE_GPIO_Port, TURN_OFF_DISCHARGE_Pin, GPIO_PIN_RESET);
	 HAL_GPIO_WritePin(TURN_ON_DISCHARGE_GPIO_Port, TURN_ON_DISCHARGE_Pin, GPIO_PIN_SET);
	 HAL_Delay(10);
	 HAL_GPIO_WritePin(TURN_ON_DISCHARGE_GPIO_Port, TURN_ON_DISCHARGE_Pin, GPIO_PIN_RESET);
}

void TURN_OFF_CHARGE_MOSFET(void){
	 HAL_GPIO_WritePin(TURN_ON_CHARGE_GPIO_Port, TURN_ON_CHARGE_Pin, GPIO_PIN_RESET);
	 HAL_GPIO_WritePin(TURN_OFF_CHARGE_GPIO_Port, TURN_OFF_CHARGE_Pin, GPIO_PIN_SET);
	 HAL_Delay(10);
	 HAL_GPIO_WritePin(TURN_OFF_CHARGE_GPIO_Port, TURN_OFF_CHARGE_Pin, GPIO_PIN_RESET);
}

void TURN_OFF_DISCHARGE_MOSFET(void){
	 HAL_GPIO_WritePin(TURN_ON_DISCHARGE_GPIO_Port, TURN_ON_DISCHARGE_Pin, GPIO_PIN_RESET);
	 HAL_GPIO_WritePin(TURN_OFF_DISCHARGE_GPIO_Port, TURN_OFF_DISCHARGE_Pin, GPIO_PIN_SET);
	 HAL_Delay(10);
	 HAL_GPIO_WritePin(TURN_OFF_DISCHARGE_GPIO_Port, TURN_OFF_DISCHARGE_Pin, GPIO_PIN_RESET);
}

void TURN_ON_PRE_CHARGE(void){
	HAL_GPIO_WritePin(TURN_ON_PRECHARGE_GPIO_Port, TURN_ON_PRECHARGE_Pin, GPIO_PIN_SET);
}

void TURN_OFF_PRE_CHARGE(void){
	HAL_GPIO_WritePin(TURN_ON_PRECHARGE_GPIO_Port, TURN_ON_PRECHARGE_Pin, GPIO_PIN_RESET);
}

void LED_ALARM_ON(void){
	HAL_GPIO_WritePin(LED_ALARM_NC3_GPIO_Port, LED_ALARM_NC3_Pin, GPIO_PIN_SET);
}

void LED_ALARM_OFF(void){
	HAL_GPIO_WritePin(LED_ALARM_NC3_GPIO_Port, LED_ALARM_NC3_Pin, GPIO_PIN_RESET);
}

void LED_OK_ON(void){
	HAL_GPIO_WritePin(LED_GREEN_BUZEER_GPIO_Port, LED_GREEN_BUZEER_Pin, GPIO_PIN_SET);
}

void LED_OK_OFF(void){
	HAL_GPIO_WritePin(LED_GREEN_BUZEER_GPIO_Port, LED_GREEN_BUZEER_Pin, GPIO_PIN_RESET);
}

void LED_DISCHARGE_ON(void){
	HAL_GPIO_WritePin(LED_DISCHARGE_NC1_GPIO_Port, LED_DISCHARGE_NC1_Pin, GPIO_PIN_SET);
}

void LED_DISCHARGE_OFF(void){
	HAL_GPIO_WritePin(LED_DISCHARGE_NC1_GPIO_Port, LED_DISCHARGE_NC1_Pin, GPIO_PIN_RESET);
}

void LED_CHARGE_ON(void){
	HAL_GPIO_WritePin(LED_CHARGE_NC2_GPIO_Port, LED_CHARGE_NC2_Pin, GPIO_PIN_SET);
}

void LED_CHARGE_OFF(void){
	HAL_GPIO_WritePin(LED_CHARGE_NC2_GPIO_Port, LED_CHARGE_NC2_Pin, GPIO_PIN_RESET);
}

